version: '3'

volumes:
  storage_mariadb:
services:
  php:
    build:
      args:
        env_file_path: ./.env.dev
        github_composer_auth: asd123fgh456
    volumes:
      - ./config:/app/config
      - ./src:/app/src
      - ./tests:/app/tests
  mariadb:
    env_file:
      - ./.env.dev
    volumes:
      - storage_mariadb:/var/lib/mysql
  mail:
    container_name: hap_mail
    image: mailhog/mailhog:latest
    ports:
      - '1025:1025'
      - '8025:8025'
  pma:
    image: phpmyadmin/phpmyadmin
    container_name: hap_pma
    environment:
      PMA_HOST: hap_mariadb
    links:
      - mariadb:db
    ports:
      - '8080:80'
    depends_on:
      - mariadb
    restart: always
